name = "preferred-domain-manager"
main = "src/main.ts"
compatibility_date = "2026-07-30"
compatibility_flags = ["nodejs_compat"]
minify = true

# 发布前执行：wrangler kv namespace create PDM_KV
[[kv_namespaces]]
binding = "PDM_KV"
id = "137a009b5cb4459a9700f515cbdf271f"

[[durable_objects.bindings]]
name = "SYNC_LOCK"
class_name = "SyncLock"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["SyncLock"]

[triggers]
crons = ["*/10 * * * *"]

