import { applyUiRedesign } from "./redesign";
import { adminBaseStyles, adminClientScript, adminEnhancementsScript } from "./admin-ui-assets";

function adminTemplate() {
  return String.raw`<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#0b1220"><title>优选域名管理面板</title>${adminBaseStyles}</head><body>
<main id="login" class="auth-shell"><section class="login"><div class="login-brand"><span class="brand-mark">优</span><div><small>Preferred Domain</small><h1>管理员登录</h1></div></div><p>登录后管理 Cloudflare DNS、优选 IP 和 Telegram Bot。</p><form id="loginForm"><label for="password">管理员密码</label><div class="password-field"><input id="password" type="password" autocomplete="current-password" placeholder="请输入 ADMIN_PASSWORD" required><button type="button" id="togglePassword" class="icon-button" aria-label="显示密码" title="显示密码">◉</button></div><button type="submit" class="login-submit">登录管理台 <span aria-hidden="true">→</span></button><div id="loginStatus" class="status" aria-live="polite"></div></form><p class="login-note">会话使用 HttpOnly Cookie 保存，登录信息不会显示在地址栏。</p></section></main>
<div id="app" class="layout hidden"><aside class="sidebar"><div class="brand"><span class="brand-mark">优</span><span>优选域名管理</span></div><nav class="nav" aria-label="主导航"><button type="button" data-page="dashboard" class="active"><span class="nav-icon">⌂</span>仪表盘</button><button type="button" data-page="settings"><span class="nav-icon">⚙</span>全局设置</button></nav></aside><div class="content"><header class="topbar"><h1 id="pageTitle">仪表盘</h1><div class="top-actions"><button type="button" id="theme" class="secondary" title="切换主题">☼ / ☾</button><button type="button" id="logout" class="secondary">退出登录</button></div></header><main class="main">
<section id="dashboard" class="page active"><div class="page-head"><div><div class="page-kicker">Overview</div><h2>仪表盘</h2><p>集中管理 DNS、优选 IP 与运行状态。</p></div><div class="status" id="domainStatus" aria-live="polite"></div></div><div class="dashboard-grid">
<section class="card span-all"><span class="section-icon">⌁</span><div class="section-head"><div><h3>DNS 编辑</h3><p>展示当前域名在 Cloudflare 中的全部 DNS 记录；开启配对时仅主域名可编辑，关闭后主域名和泛域名可独立编辑。</p></div><div class="actions"><button type="button" id="refreshDns" class="secondary">↻ 刷新</button><button type="button" id="addDns">＋ 新建记录</button></div></div><div class="toolbar"><div class="toolbar-left"><label class="sr-only" for="dnsFilter">搜索 DNS 记录</label><input id="dnsFilter" placeholder="搜索类型、内容或名称"><span id="dnsStatus" class="status" aria-live="polite"></span></div></div><div class="table-wrap"><table class="table"><thead><tr><th>类型</th><th>名称</th><th>内容</th><th>TTL</th><th>代理</th><th>来源</th><th>操作</th></tr></thead><tbody id="dnsRows"><tr><td colspan="7" class="empty">正在加载 DNS 记录…</td></tr></tbody></table></div></section>
<section class="card span-all"><span class="section-icon">◈</span><div class="section-head"><div><h3>Cloudflare 连接</h3><p>设置保存到 KV，用于 DNS 编辑与优选 IP 同步。敏感 Token 只显示配置状态。</p></div><span id="runtimeStatus" class="status" aria-live="polite"></span></div><div class="row"><div><label for="defaultDomain">默认域名</label><input id="defaultDomain" placeholder="example.com" autocomplete="off"></div><div><label for="cfZoneId">Cloudflare Zone ID</label><input id="cfZoneId" placeholder="Zone ID" autocomplete="off"></div><div><label for="cfApiToken">Cloudflare API Token</label><input id="cfApiToken" type="password" placeholder="留空保持已有 Token" autocomplete="off"></div></div><div class="actions" style="margin-top:14px"><button type="button" id="saveRuntime">保存连接设置</button><span class="hint">Token 至少需要 Zone Read 和 DNS Edit 权限。</span></div><div class="metrics"><div class="metric"><strong id="dnsCount">—</strong><span>可管理 DNS 记录</span></div><div class="metric"><strong id="sourceCount">—</strong><span>已配置 IP 来源</span></div><div class="metric"><strong id="manualCount">—</strong><span>手动 IP 数量</span></div></div></section>
<section class="card"><span class="section-icon">◎</span><div class="section-head"><div><h3>IP 来源</h3><p>支持 JSON、纯文本及嵌套数组。</p></div></div><div id="sources"></div><button type="button" id="addSource" class="secondary">＋ 添加来源</button></section>
<section class="card"><span class="section-icon">✦</span><div class="section-head"><div><h3>手动优选 IP</h3><p>每行一个 IPv4 或 IPv6，会与来源结果合并去重。</p></div></div><textarea id="manualIps" placeholder="1.1.1.1&#10;2606:4700:4700::1111"></textarea></section>
<section class="card span-all"><span class="section-icon">↯</span><div class="section-head"><div><h3>优选 IP 操作</h3><p>同步前会检测 TCP 443；没有通过项时不会改动现有 DNS。</p></div></div><div class="actions"><button type="button" id="saveConfig">保存全部配置</button><button type="button" id="preview" class="secondary">检测优选 IP</button><button type="button" id="sync">立即同步 DNS</button><span id="status" class="status" aria-live="polite"></span></div><pre id="output" class="card output">等待操作…</pre></section>
</div></section>
<section id="settings" class="page"><div class="page-head"><div><div class="page-kicker">Configuration</div><h2>全局设置</h2><p>配置 Telegram Bot，并将设置安全保存到 KV。</p></div></div><section class="card"><span class="section-icon">✈</span><div class="section-head"><div><h3>Telegram Bot</h3><p>通过 Telegram 查看、添加、修改和删除默认域名记录，泛记录会自动同步。只有白名单用户可以操作。</p></div><span id="telegramStatus" class="status" aria-live="polite"></span></div><label for="telegramBotToken">Bot Token</label><input id="telegramBotToken" type="password" autocomplete="off" placeholder="留空保持已有 Token"><label for="telegramWebhookSecret">Webhook Secret</label><input id="telegramWebhookSecret" type="password" autocomplete="off" placeholder="留空保持已有 Secret"><label for="telegramAllowedUserIds">允许的 Telegram 用户 ID</label><textarea id="telegramAllowedUserIds" placeholder="例如：123456789&#10;每行一个，也支持逗号或空格分隔"></textarea><p id="telegramConfigStatus" class="hint"></p><div class="actions"><button type="button" id="saveTelegram">保存 Telegram 设置</button><button type="button" id="telegramTest" class="secondary">测试 Bot</button><button type="button" id="telegramSetWebhook" class="secondary">设置 Webhook</button><button type="button" id="telegramDeleteWebhook" class="danger">删除 Webhook</button><button type="button" id="telegramCommands" class="secondary">同步菜单命令</button></div><p class="hint">Webhook 地址为当前 Worker 域名下的 <code>/telegram/webhook</code>。请先保存 Token、Secret 和用户 ID。</p></section></section>
</main></div></div><dialog id="dnsDialog" class="dialog"><form id="dnsForm"><div class="dialog-body"><div class="dialog-head"><h3 id="dnsDialogTitle">新建 DNS 记录</h3><button type="button" id="closeDns" class="close" aria-label="关闭">×</button></div><p class="hint">保存时会根据内容自动识别为 A、AAAA 或 CNAME。</p><label for="dnsType">记录类型</label><select id="dnsType"><option>A</option><option>AAAA</option><option>CNAME</option></select><p id="dnsRuleHint" class="hint">名称固定为默认域名；保存后会自动同步对应泛记录。</p><label for="dnsName">主域名</label><input id="dnsName" readonly required><label for="dnsContent">内容</label><textarea id="dnsContent" placeholder="输入 IPv4、IPv6 地址或目标域名" required></textarea><div class="row"><div><label for="dnsTtl">TTL</label><input id="dnsTtl" value="最低（60 秒）" disabled></div><label class="check"><input id="dnsProxied" type="checkbox" disabled>固定 DNS only（灰云）</label></div><div class="dialog-actions"><button type="button" id="cancelDns" class="secondary">取消</button><button type="submit" id="saveDns">保存记录</button></div></div></form></dialog><div id="toastRegion" class="toast-region" aria-live="polite" aria-atomic="true"></div>${adminClientScript}${adminEnhancementsScript}</body></html>`;
}

export function adminPage() {
  return applyUiRedesign(adminTemplate(), "admin");
}


