export const adminLayoutScript = String.raw`
const adminLayoutStyle=document.createElement('style');adminLayoutStyle.textContent='.page.active:not(#settings){display:grid;gap:18px}.page.active:not(#settings)>.page-head{margin-bottom:0}.page.active:not(#settings)>.card{width:100%}.dashboard-overview{min-height:180px}.dashboard-overview .actions{margin-top:18px}.source{grid-template-columns:minmax(0,1.45fr) minmax(0,1fr) auto auto}.source .s-note{min-width:0}.source .s-enabled{width:auto}@media(max-width:640px){.source{grid-template-columns:minmax(0,1fr) auto}.source .s-note{grid-column:1/-1}.source .s-enabled{grid-column:2}.source .remove-source{grid-column:1/-1;justify-self:start}}';document.head.append(adminLayoutStyle);

const adminMain=document.querySelector('.main');const dashboardPage=document.querySelector('#dashboard');const settingsPage=document.querySelector('#settings');const dashboardGrid=dashboardPage?.querySelector('.dashboard-grid');const dashboardCards=dashboardGrid?[...dashboardGrid.children]:[];const dnsCard=dashboardCards[0];const cloudflareCard=dashboardCards[1];const apiConfigCard=dashboardCards[2];const manualConfigCard=dashboardCards[3];const preferredActionsCard=dashboardCards[4];
const createAdminPage=(id,kicker,title,description)=>{const page=document.createElement('section');page.id=id;page.className='page';page.innerHTML='<div class="page-head"><div><div class="page-kicker">'+kicker+'</div><h2>'+title+'</h2><p>'+description+'</p></div><div class="status" id="'+id+'Status" aria-live="polite"></div></div>';return page;};
if(adminMain&&dashboardPage&&settingsPage){const preferredPanelPage=createAdminPage('preferred-panel','Preferred Panel','优选面板','检测优选 IP 并将通过检测的地址同步到 DNS。');const dnsPage=createAdminPage('dns-editor','DNS Editor','DNS 编辑','查看和维护当前域名的 DNS 记录。');const preferredConfigPage=createAdminPage('preferred-config','Preferred Config','优选配置','配置优选 API 和手动优选 IP。');adminMain.insertBefore(preferredPanelPage,settingsPage);adminMain.insertBefore(dnsPage,settingsPage);adminMain.insertBefore(preferredConfigPage,settingsPage);if(preferredActionsCard)preferredPanelPage.append(preferredActionsCard);if(dnsCard)dnsPage.append(dnsCard);if(apiConfigCard)preferredConfigPage.append(apiConfigCard);if(manualConfigCard)preferredConfigPage.append(manualConfigCard);if(cloudflareCard){cloudflareCard.classList.add('settings-card');settingsPage.insertBefore(cloudflareCard,settingsPage.children[1]||null);}dashboardGrid?.remove();const overview=document.createElement('section');overview.className='card dashboard-overview';overview.innerHTML='<span class="section-icon">⌂</span><div class="section-head"><div><h3>优选域名管理</h3><p>从这里进入优选面板、DNS 编辑、优选配置或全局设置。</p></div></div><div class="actions"><button type="button" class="secondary" data-go-page="preferred-panel">打开优选面板</button><button type="button" class="secondary" data-go-page="preferred-config">管理优选配置</button></div>';dashboardPage.append(overview);}

const adminNavItems=[['dashboard','⌂','仪表盘'],['preferred-panel','↯','优选面板'],['dns-editor','⌁','DNS 编辑'],['preferred-config','✦','优选配置'],['settings','⚙','全局设置']];const adminNav=document.querySelector('.nav');if(adminNav)adminNav.innerHTML=adminNavItems.map(item=>'<button type="button" data-page="'+item[0]+'"><span class="nav-icon">'+item[1]+'</span>'+item[2]+'</button>').join('');const mobileNav=document.querySelector('#mobileMenu');if(mobileNav)mobileNav.innerHTML=adminNavItems.map(item=>'<button type="button" data-page="'+item[0]+'"><span class="nav-icon">'+item[1]+'</span>'+item[2]+'</button>').join('');document.querySelectorAll('.nav button,#mobileMenu button').forEach(button=>button.addEventListener('click',()=>showPage(button.dataset.page)));document.querySelectorAll('[data-go-page]').forEach(button=>button.addEventListener('click',()=>showPage(button.dataset.goPage)));
const adminPageTitles={dashboard:'仪表盘','preferred-panel':'优选面板','dns-editor':'DNS 编辑','preferred-config':'优选配置',settings:'全局设置'};const pageAliases={preferredPanel:'preferred-panel',dnsEditor:'dns-editor',preferredConfig:'preferred-config'};const normalizeAdminPage=page=>pageAliases[page]||page;const previousShowPage=showPage;showPage=page=>{const target=normalizeAdminPage(page);const valid=adminPageTitles[target]?target:'dashboard';previousShowPage(valid);$('#pageTitle').textContent=adminPageTitles[valid];if(valid==='dns-editor')loadDns();document.querySelectorAll('.nav button,#mobileMenu button').forEach(button=>button.classList.toggle('active',button.dataset.page===valid));};const requestedAdminPage=normalizeAdminPage(location.hash.slice(1));showPage(adminPageTitles[requestedAdminPage]?requestedAdminPage:'dashboard');

const preferredApiCard=document.querySelector('#sources')?.closest('.card');if(preferredApiCard){const heading=preferredApiCard.querySelector('h3');if(heading)heading.textContent='优选 API 配置';const description=preferredApiCard.querySelector('.section-head p');if(description)description.textContent='配置获取优选 IP 的 API 地址，可为每个 API 添加备注。';const saveButton=document.querySelector('#saveSources');if(saveButton)saveButton.textContent='保存优选 API 配置';}
const baseRenderConfigWithNotes=renderConfig;renderConfig=()=>{baseRenderConfigWithNotes();document.querySelectorAll('.source').forEach((row,index)=>{if(row.querySelector('.s-note'))return;const note=document.createElement('input');note.className='s-note';note.placeholder='备注（可选）';note.value=state.ipSources[index]?.note||'';note.maxLength=120;const enabled=row.querySelector('.s-enabled')?.parentElement;if(enabled)row.insertBefore(note,enabled);else row.append(note);});};const baseReadConfigWithNotes=readConfig;readConfig=()=>{baseReadConfigWithNotes();state.ipSources=state.ipSources.map((source,index)=>({...source,note:document.querySelector('.source[data-index="'+index+'"] .s-note')?.value.trim().slice(0,120)||''}));};
const preferredConfigSaveActions=document.createElement('div');preferredConfigSaveActions.className='actions preferred-config-save';preferredConfigSaveActions.innerHTML='<button type="button" id="savePreferredConfig">保存优选配置</button><span id="preferredConfigStatus" class="status" aria-live="polite"></span>';document.querySelector('#manualIps')?.closest('.card')?.after(preferredConfigSaveActions);document.querySelector('#savePreferredConfig')?.addEventListener('click',()=>saveConfig($('#preferredConfigStatus'),'保存优选配置'));
async function savePreferredApiConfig(){if(sourceBusy)return;sourceBusy=true;setBusy('#saveSources',true);try{setStatus($('#sourceStatus'),'保存优选 API 配置中…');readConfig();const urls=state.ipSources.map(source=>source.url.toLowerCase()),duplicate=urls.find((url,index)=>url&&urls.indexOf(url)!==index);if(duplicate)throw Error('优选 API 地址不能重复：'+duplicate);const invalid=state.ipSources.find(source=>{try{const parsed=new URL(source.url);return !['http:','https:'].includes(parsed.protocol)||!parsed.hostname;}catch{return true;}});if(invalid)throw Error('优选 API 地址无效：'+invalid.url);Object.assign(state,await api('/api/ip-sources',{method:'PUT',body:JSON.stringify({ipSources:state.ipSources})}));renderConfig();setStatus($('#sourceStatus'),'优选 API 配置已保存，未自动获取 IP');notify('优选 API 配置已保存');}catch(error){const message=error instanceof Error?error.message:String(error);setStatus($('#sourceStatus'),message,true);notify(message,'error');}finally{sourceBusy=false;setBusy('#saveSources',false);}}
const savePreferredApiButton=document.querySelector('#saveSources');if(savePreferredApiButton)savePreferredApiButton.addEventListener('click',event=>{event.preventDefault();event.stopImmediatePropagation();void savePreferredApiConfig();},true);
const preferredActionsHeading=preferredActionsCard?.querySelector('h3');if(preferredActionsHeading)preferredActionsHeading.textContent='优选面板';const manualConfigHeading=manualConfigCard?.querySelector('h3');if(manualConfigHeading)manualConfigHeading.textContent='手动优选 IP 配置';if(cloudflareCard&&dashboardPage){cloudflareCard.classList.remove('settings-card');dashboardPage.append(cloudflareCard);}document.querySelector('.dashboard-overview')?.remove();
const dnsTypeOrder={A:0,AAAA:1,CNAME:2};const dnsRecordName=value=>String(value||'').trim().toLowerCase().replace(/\.$/,'');const compareDnsRecords=(left,right)=>{const domain=dnsRecordName(state.defaultDomain);const leftName=dnsRecordName(left.name);const rightName=dnsRecordName(right.name);const leftRoot=leftName===domain?0:1;const rightRoot=rightName===domain?0:1;if(leftRoot!==rightRoot)return leftRoot-rightRoot;const leftType=dnsTypeOrder[left.type]??99;const rightType=dnsTypeOrder[right.type]??99;if(leftType!==rightType)return leftType-rightType;const nameCompare=leftName.localeCompare(rightName);if(nameCompare!==0)return nameCompare;return String(left.content||'').localeCompare(String(right.content||''));};const renderDnsWithPreferredOrder=renderDns;renderDns=()=>{dnsState.records.sort(compareDnsRecords);renderDnsWithPreferredOrder();};
`;
