import { escapeHtml } from "../validation";
import { applyUiRedesign } from "./redesign";

function landingTemplate(host: string, adminPath = "/admin") {
  return `<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#0b1220"><title>优选域名管理面板</title><style>
:root{color-scheme:dark;--bg:#08111f;--panel:#101b2d;--text:#edf3ff;--muted:#91a2bc;--border:#263956;--primary:#6b82ff;--primary-2:#8f6dff;--shadow:0 24px 80px #0005}*{box-sizing:border-box}body{margin:0;min-height:100vh;background:radial-gradient(circle at 12% 0,#536dff2b,transparent 34%),radial-gradient(circle at 100% 12%,#9a65ff1f,transparent 30%),var(--bg);color:var(--text);font:15px/1.6 system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}main{width:min(760px,100%);margin:auto;padding:clamp(36px,15vh,150px) 20px}.landing-card{position:relative;overflow:hidden;border:1px solid #526fd166;background:linear-gradient(145deg,#111d32eF,#0d1728f5);border-radius:28px;padding:clamp(28px,6vw,58px);box-shadow:var(--shadow)}.landing-card:after{content:"";position:absolute;width:260px;height:260px;right:-130px;top:-140px;border-radius:50%;background:#7668ff2a;filter:blur(8px)}.landing-card>*{position:relative;z-index:1}.eyebrow{display:inline-flex;align-items:center;gap:8px;color:#aebaff;font-size:12px;font-weight:700;letter-spacing:.12em;text-transform:uppercase}.eyebrow:before{content:"";width:8px;height:8px;border-radius:50%;background:#53d9a4;box-shadow:0 0 0 5px #53d9a422}.brand-mark{display:flex;align-items:center;justify-content:center;width:58px;height:58px;margin:24px 0 22px;border-radius:18px;background:linear-gradient(135deg,var(--primary),var(--primary-2));font-size:25px;font-weight:800;box-shadow:0 14px 32px #6b82ff55}.landing-card h1{max-width:560px;margin:0;font-size:clamp(30px,6vw,48px);line-height:1.12;letter-spacing:-.04em}.landing-card p{max-width:580px;color:var(--muted);font-size:16px}.landing-card strong{color:var(--text)}.feature-row{display:flex;flex-wrap:wrap;gap:10px;margin:26px 0}.feature{padding:9px 12px;border:1px solid var(--border);border-radius:12px;color:#bac7dc;background:#ffffff06;font-size:13px}.landing-card a{display:inline-flex;align-items:center;gap:9px;margin-top:8px;padding:12px 16px;border-radius:12px;color:#fff;background:linear-gradient(135deg,var(--primary),var(--primary-2));font-weight:700;text-decoration:none;box-shadow:0 10px 26px #6b82ff33;transition:transform .18s,box-shadow .18s}.landing-card a:hover{transform:translateY(-2px);box-shadow:0 15px 32px #6b82ff55}.landing-card small{display:block;margin-top:24px;color:#71819c}
</style></head><body><main><section class="landing-card"><div class="eyebrow">Preferred Domain Manager</div><div class="brand-mark">优</div><h1>简洁、安全的优选域名管理</h1><p>欢迎访问 <strong>${escapeHtml(host)}</strong>。DNS、优选 IP 与 Telegram Bot 均可在统一管理台中配置。</p><div class="feature-row"><span class="feature">Cloudflare DNS</span><span class="feature">A / AAAA / CNAME</span><span class="feature">Telegram Bot</span></div><a href="${escapeHtml(adminPath)}">进入管理台 <span aria-hidden="true">→</span></a><small>根域名与泛域名均可绑定到当前 Worker。</small></section></main></body></html>`;
}


export function landingPage(host: string, adminPath = "/admin") {
  return applyUiRedesign(landingTemplate(host, adminPath), "landing");
}

